---
# tasks file for ansible-role-pam

- name: template pam.d system-auth
  template: src=system-auth.j2 dest=/etc/pam.d/system-auth
            owner=root group=root mode=644
  when: pam_enabled

- name: template pam.d system-auth-ac
  template: src=system-auth.j2 dest=/etc/pam.d/system-auth-ac
            owner=root group=root mode=644
  when: pam_enabled

- name: template pam.d password-auth
  template: src=system-auth.j2 dest=/etc/pam.d/password-auth
            owner=root group=root mode=644
  when: pam_enabled

- name: template /etc/security/namespace.d/site.conf
  template: src=site.conf.j2 dest=/etc/security/namespace.d/site.conf
            owner=root group=root mode=644
  when: pam_enabled
